---
name: Staging Deployment

on:
  push:
    branches:
      - staging

  workflow_dispatch:

jobs:
  build:
    outputs:
      image: ${{ steps.export.outputs.image }}
      tag: ${{ steps.export.outputs.tag }}

    runs-on: ubuntu-latest
    env:
      image: cranecloud/mlops-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install (Buildx)
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: meta
        name: Tag
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=true
          images: ${{ env.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Build
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - id: export
        name: Export
        uses: actions/github-script@v7
        with:
          script: |
            const metadata = JSON.parse(`${{ steps.meta.outputs.json }}`)
            const fullUrl = metadata.tags.find((t) => t.includes(':sha-'))
            if (fullUrl == null) {
              core.error('Unable to find sha tag of image')
            } else {
              const tag = fullUrl.split(':')[1]
              core.setOutput('image', fullUrl)
              core.setOutput('tag', tag)
            }

  Staging:
    name: Deploy (Staging)

    needs:
      - Build

    runs-on: ubuntu-latest
    env:
      namespace: cranecloud-microservice
      image: cranecloud/mlops-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.RENU_KUBECONFIG}}

      - name: Add Repo (cranecloud)
        run: |
          helm repo add cranecloud https://crane-cloud.github.io/helm-charts/

      - name: Helm Release
        run: |
          helm upgrade --install --create-namespace \
          mlops-api cranecloud/cranecloud \
          --values helm/values.staging.yaml \
          --namespace $namespace \
          --set image.tag="${{ needs.build.outputs.tag }}" \
          --set environment.DATABASE_URI="${{ secrets.STAGING_DATABASE_URI }}" \
          --set environment.FLASK_APP_SALT="${{ secrets.STAGING_FLASK_APP_SALT }}" \
          --set environment.PRODUCT_BASE_URL="${{ secrets.STAGING_PRODUCT_BASE_URL }}" \
          --timeout=300s

      - name: Monitor Rollout
        run: |
          kubectl rollout status deployment/mlops-api --timeout=300s --namespace $namespace
